import Encabezado from "../Encabezado";
import Navegador from "../Navegador";
import Post from "../Post";

export default function Home(){
    return (
        <div>
            <Navegador />
            <Encabezado />
            <Post titulo='Los gatos... ¿Tiene 7 vidas?' descripcion='La famosa frase, ya popularizada, sobre que "los gatos tienen siete vidas", es otra características tomada por quienes consideran que estos felinos no son solo animales comunes y corrientes, sino que tienen un objetivo en el planeta Tierra y la misión la están cumpliendo... Muchas son las anécdotas que cuentan las personas que poseen gatos o no, pero que alguna vez vieron como un felino pasó por un accidente que terminaría con su vida, pero de todas formas allí está, continúa "vivito y coleando" como si nada hubiese pasado y no existe explicación alguna a lo sucedido. ¿Cómo un gato que cae de un quinto piso puede seguir vivo y sin ningún tipo de lesión? ¿Tan fuerte y resistente son sus patas como su cuerpo para no sentir el impacto? Más allá de las habilidades en todas las razas felinas, existe una especie, Sphynx, que es sin pelo y son los que más se aproximan físicamente a los clásicos alienígenas grises, o al menos eso dicen algunos creyentes de la teoría de que los gatos son alienígenas o seres que conectan con ellos. ¿La gatos serán extraterrestres que viven camuflados entre nosotros?' link="/UnPost"/>
            <Post titulo='La teoria de los gatos extraterrestres' descripcion='Sé que muchos me tomaréis por loco, o que pretendo haceros una broma. Pero no, no es así. Yo soy un gran observador de la vida, de la realidad, y bajo la realidad cotidiana existen misterios, ecos, destellos de otras realidades más sutiles, fuera del alcance de las vistas acomodadas y superficiales. Yo, gracias a mi capacidad de observación y análisis, he ido desarrollando esta teoría con los años y al final la verdad se ha mostrado ante mis ojos al principio escépticos. Aún no me atrevo a calificar dicha revelación como divina, pero casi, casi. Gracias a ExpertoAnimal, a pesar de que no están convencidos de mi visión, os podré argumentar diversos hechos que avalan mi teoría de los gatos extraterrestres, fruto del estudio y la dilatada convivencia con dichos seres.' link="/SdoPost"/>
            <Post titulo='Los gatos Sphynx son los extraterrestres Grises' descripcion='Los gatos de la raza Sphynx no tienen pelo en su cuerpo. La raza alienígena de los Grises es una raza sin nada de pelo. La conclusión es que los Grises llegaron a Egipto y se quedaron, siendo los primeros gatos. Por eso, el nombre de la raza es sospechosamente Sphynx, Esfinge o Gato Egipcio. La raza Sphynx fue creada en Canadá en los años 60 del siglo XX, por selección genética humana, donde los criadores se centraron en encontrar y mantener el gen mutante recesivo de la carencia de pelaje. Además, hay que decir que existen grabados aztecas donde ya aparecen gatos sin pelo y un biólogo alemán, Rudolph Renger, incluyó a los gatos sin pelo en su libro Historia natural de los maíferos de Paraguay en 1830, confirmando otra vez que ya había gatos sin pelo en América desde hacía siglos.' link="/TcerPost"/>
        </div>
    );
}